name: Limpar Repositório

on:
  workflow_dispatch:  # Permite executar manualmente

permissions:
  contents: write  # Permissão para modificar o repositório

jobs:
  limpeza:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Usa o token do GitHub com permissões de escrita

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Listar arquivos antes da remoção
        run: ls -la  # Mostra os arquivos presentes antes de tentar remover

      - name: Remover todos os arquivos e pastas (exceto .github)
        run: |
          # Remove tudo no nível raiz, exceto .github e .git
          find . -mindepth 1 -maxdepth 1 -not -name ".github" -not -name ".git" -exec rm -rf {} +
          # Garante que a pasta .github não seja afetada

      - name: Listar arquivos após a remoção
        run: ls -la  # Mostra o estado após a remoção

      - name: Commit e push das mudanças
        run: |
          git add .
          git commit -m "Limpeza manual do repositório (preservando .github)" || echo "Nenhuma mudança para commitar"
          git push origin HEAD --force  # Força o push para a branch atual
